// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WorkFlow.Infrastructure.Persistence;

#nullable disable

namespace WorkFlow.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(WorkFlowDbContext))]
    [Migration("20260827183537_AddNormalizedEmailToUsers")]
    partial class AddNormalizedEmailToUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WorkFlow.Domain.Entities.ChatMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AuthorUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("author_user_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<long?>("DeletedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("deleted_by_user_id");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_chat_messages");

                    b.HasIndex("AuthorUserId")
                        .HasDatabaseName("ix_chat_messages_author_user_id");

                    b.HasIndex("DeletedByUserId")
                        .HasDatabaseName("ix_chat_messages_deleted_by_user_id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_chat_messages_expires_at");

                    b.HasIndex("TenantId", "CreatedAt")
                        .HasDatabaseName("ix_chat_messages_tenant_id_created_at");

                    b.ToTable("chat_messages", (string)null);
                });

            modelBuilder.Entity("WorkFlow.Domain.Entities.Notification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("ActorUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("actor_user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DismissedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dismissed_at");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<long>("RecipientUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("recipient_user_id");

                    b.Property<long?>("ResourceId")
                        .HasColumnType("bigint")
                        .HasColumnName("resource_id");

                    b.Property<int?>("ResourceType")
                        .HasColumnType("integer")
                        .HasColumnName("resource_type");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("ActorUserId")
                        .HasDatabaseName("ix_notifications_actor_user_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_notifications_created_at");

                    b.HasIndex("RecipientUserId", "CreatedAt")
                        .HasDatabaseName("ix_notifications_recipient_user_id_created_at");

                    b.HasIndex("ResourceType", "ResourceId")
                        .HasDatabaseName("ix_notifications_resource_type_resource_id")
                        .HasFilter("resource_type IS NOT NULL AND resource_id IS NOT NULL");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("WorkFlow.Domain.Entities.Project", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CreatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id");

                    b.Property<long?>("ResponsibleUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("responsible_user_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int?>("StatusBeforeArchive")
                        .HasColumnType("integer")
                        .HasColumnName("status_before_archive");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_projects");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_projects_created_by_user_id");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ux_projects_public_id");

                    b.HasIndex("ResponsibleUserId")
                        .HasDatabaseName("ix_projects_responsible_user_id");

                    b.HasIndex("TenantId", "DueDate")
                        .HasDatabaseName("ix_projects_tenant_id_due_date");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_projects_tenant_id_status");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("WorkFlow.Domain.Entities.ProjectHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Action")
                        .HasColumnType("integer")
                        .HasColumnName("action");

                    b.Property<long>("ActorUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("actor_user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("NewValue")
                        .HasColumnType("text")
                        .HasColumnName("new_value");

                    b.Property<string>("OldValue")
                        .HasColumnType("text")
                        .HasColumnName("old_value");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_id");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.HasKey("Id")
                        .HasName("pk_project_histories");

                    b.HasIndex("ActorUserId")
                        .HasDatabaseName("ix_project_histories_actor_user_id");

                    b.HasIndex("ProjectId", "CreatedAt")
                        .HasDatabaseName("ix_project_histories_project_id_created_at");

                    b.ToTable("project_histories", (string)null);
                });

            modelBuilder.Entity("WorkFlow.Domain.Entities.ProjectMember", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.Property<long>("AddedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("added_by_user_id");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_id");

                    b.Property<DateTime?>("RemovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("removed_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_project_members");

                    b.HasIndex("AddedByUserId")
                        .HasDatabaseName("ix_project_members_added_by_user_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_project_members_user_id");

                    b.HasIndex("ProjectId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_project_members_active")
                        .HasFilter("removed_at IS NULL");

                    b.ToTable("project_members", (string)null);
                });

            modelBuilder.Entity("WorkFlow.Domain.Entities.ProjectMemberPermission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at");

                    b.Property<long>("GrantedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("granted_by_user_id");

                    b.Property<int>("Permission")
                        .HasColumnType("integer")
                        .HasColumnName("permission");

                    b.Property<long>("ProjectMemberId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_member_id");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<long?>("RevokedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("revoked_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_project_member_permissions");

                    b.HasIndex("GrantedByUserId")
                        .HasDatabaseName("ix_project_member_permissions_granted_by");

                    b.HasIndex("RevokedByUserId")
                        .HasDatabaseName("ix_project_member_permissions_revoked_by");

                    b.HasIndex("ProjectMemberId", "Permission")
                        .IsUnique()
                        .HasDatabaseName("ux_project_member_permissions_active")
                        .HasFilter("revoked_at IS NULL");

                    b.ToTable("project_member_permissions", (string)null);
                });

            modelBuilder.Entity("WorkFlow.Domain.Entities.ProjectTask", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CreatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_date");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_id");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id");

                    b.Property<long?>("ResponsibleUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("responsible_user_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int?>("StatusBeforePause")
                        .HasColumnType("integer")
                        .HasColumnName("status_before_pause");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long?>("ValidatorUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("validator_user_id");

                    b.HasKey("Id")
                        .HasName("pk_project_tasks");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_project_tasks_created_by_user_id");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ux_project_tasks_public_id");

                    b.HasIndex("ProjectId", "DueDate")
                        .HasDatabaseName("ix_project_tasks_project_id_due_date");

                    b.HasIndex("ProjectId", "Status")
                        .HasDatabaseName("ix_project_tasks_project_id_status");

                    b.HasIndex("ResponsibleUserId", "Status")
                        .HasDatabaseName("ix_project_tasks_responsible_status");

                    b.HasIndex("ValidatorUserId", "Status")
                        .HasDatabaseName("ix_project_tasks_validator_status");

                    b.ToTable("project_tasks", (string)null);
                });

            modelBuilder.Entity("WorkFlow.Domain.Entities.TaskCollaborator", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.Property<long>("AddedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("added_by_user_id");

                    b.Property<DateTime?>("RemovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("removed_at");

                    b.Property<long?>("RemovedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("removed_by_user_id");

                    b.Property<long>("TaskId")
                        .HasColumnType("bigint")
                        .HasColumnName("task_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_task_collaborators");

                    b.HasIndex("AddedByUserId")
                        .HasDatabaseName("ix_task_collaborators_added_by_user_id");

                    b.HasIndex("RemovedByUserId")
                        .HasDatabaseName("ix_task_collaborators_removed_by_user_id");

                    b.HasIndex("TaskId")
                        .HasDatabaseName("ix_task_collaborators_task_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_task_collaborators_user_id");

                    b.HasIndex("TaskId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_task_collaborators_task_id_user_id_active")
                        .HasFilter("removed_at IS NULL");

                    b.ToTable("task_collaborators", (string)null);
                });

            modelBuilder.Entity("WorkFlow.Domain.Entities.TaskComment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AuthorUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("author_user_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<long?>("DeletedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("deleted_by_user_id");

                    b.Property<long>("TaskId")
                        .HasColumnType("bigint")
                        .HasColumnName("task_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_task_comments");

                    b.HasIndex("AuthorUserId")
                        .HasDatabaseName("ix_task_comments_author_user_id");

                    b.HasIndex("DeletedByUserId")
                        .HasDatabaseName("ix_task_comments_deleted_by_user_id");

                    b.HasIndex("TaskId", "CreatedAt")
                        .HasDatabaseName("ix_task_comments_task_id_created_at");

                    b.ToTable("task_comments", (string)null);
                });

            modelBuilder.Entity("WorkFlow.Domain.Entities.TaskHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Action")
                        .HasColumnType("integer")
                        .HasColumnName("action");

                    b.Property<long>("ActorUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("actor_user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("NewValue")
                        .HasColumnType("text")
                        .HasColumnName("new_value");

                    b.Property<string>("OldValue")
                        .HasColumnType("text")
                        .HasColumnName("old_value");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<long>("TaskId")
                        .HasColumnType("bigint")
                        .HasColumnName("task_id");

                    b.HasKey("Id")
                        .HasName("pk_task_histories");

                    b.HasIndex("ActorUserId")
                        .HasDatabaseName("ix_task_histories_actor_user_id");

                    b.HasIndex("TaskId", "CreatedAt")
                        .HasDatabaseName("ix_task_histories_task_id_created_at");

                    b.ToTable("task_histories", (string)null);
                });

            modelBuilder.Entity("WorkFlow.Domain.Entities.Tenant", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("registration_number");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ux_tenants_public_id");

                    b.HasIndex("RegistrationNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_tenants_registration_number");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("WorkFlow.Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("normalized_email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<long?>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ux_users_system_admin_normalized_email")
                        .HasFilter("tenant_id IS NULL");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ux_users_public_id");

                    b.HasIndex("TenantId", "NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ux_users_tenant_id_normalized_email")
                        .HasFilter("tenant_id IS NOT NULL");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("WorkFlow.Domain.Entities.ChatMessage", b =>
                {
                    b.HasOne("WorkFlow.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("AuthorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_chat_messages_users_author_user_id");

                    b.HasOne("WorkFlow.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("DeletedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_chat_messages_users_deleted_by_user_id");

                    b.HasOne("WorkFlow.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_chat_messages_tenants_tenant_id");
                });

            modelBuilder.Entity("WorkFlow.Domain.Entities.Notification", b =>
                {
                    b.HasOne("WorkFlow.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_notifications_users_actor_user_id");

                    b.HasOne("WorkFlow.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("RecipientUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_users_recipient_user_id");
                });

            modelBuilder.Entity("WorkFlow.Domain.Entities.Project", b =>
                {
                    b.HasOne("WorkFlow.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_projects_created_by_users");

                    b.HasOne("WorkFlow.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ResponsibleUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_projects_responsible_users");

                    b.HasOne("WorkFlow.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_projects_tenants");
                });

            modelBuilder.Entity("WorkFlow.Domain.Entities.ProjectHistory", b =>
                {
                    b.HasOne("WorkFlow.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_project_histories_users_actor_user_id");

                    b.HasOne("WorkFlow.Domain.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_project_histories_projects_project_id");
                });

            modelBuilder.Entity("WorkFlow.Domain.Entities.ProjectMember", b =>
                {
                    b.HasOne("WorkFlow.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("AddedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_project_members_added_by_users");

                    b.HasOne("WorkFlow.Domain.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_project_members_projects");

                    b.HasOne("WorkFlow.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_project_members_users");
                });

            modelBuilder.Entity("WorkFlow.Domain.Entities.ProjectMemberPermission", b =>
                {
                    b.HasOne("WorkFlow.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("GrantedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_project_member_permissions_granted_by_users");

                    b.HasOne("WorkFlow.Domain.Entities.ProjectMember", null)
                        .WithMany()
                        .HasForeignKey("ProjectMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_project_member_permissions_members");

                    b.HasOne("WorkFlow.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("RevokedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_project_member_permissions_revoked_by_users");
                });

            modelBuilder.Entity("WorkFlow.Domain.Entities.ProjectTask", b =>
                {
                    b.HasOne("WorkFlow.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_project_tasks_created_by_users");

                    b.HasOne("WorkFlow.Domain.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_project_tasks_projects");

                    b.HasOne("WorkFlow.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ResponsibleUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_project_tasks_responsible_users");

                    b.HasOne("WorkFlow.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ValidatorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_project_tasks_validator_users");
                });

            modelBuilder.Entity("WorkFlow.Domain.Entities.TaskCollaborator", b =>
                {
                    b.HasOne("WorkFlow.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("AddedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_task_collaborators_users_added_by_user_id");

                    b.HasOne("WorkFlow.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("RemovedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_task_collaborators_users_removed_by_user_id");

                    b.HasOne("WorkFlow.Domain.Entities.ProjectTask", null)
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_task_collaborators_project_tasks_task_id");

                    b.HasOne("WorkFlow.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_task_collaborators_users_user_id");
                });

            modelBuilder.Entity("WorkFlow.Domain.Entities.TaskComment", b =>
                {
                    b.HasOne("WorkFlow.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("AuthorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_task_comments_users_author_user_id");

                    b.HasOne("WorkFlow.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("DeletedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_task_comments_users_deleted_by_user_id");

                    b.HasOne("WorkFlow.Domain.Entities.ProjectTask", null)
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_task_comments_project_tasks_task_id");
                });

            modelBuilder.Entity("WorkFlow.Domain.Entities.TaskHistory", b =>
                {
                    b.HasOne("WorkFlow.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_task_histories_users_actor_user_id");

                    b.HasOne("WorkFlow.Domain.Entities.ProjectTask", null)
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_task_histories_project_tasks_task_id");
                });

            modelBuilder.Entity("WorkFlow.Domain.Entities.User", b =>
                {
                    b.HasOne("WorkFlow.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .HasConstraintName("fk_users_tenants");
                });
#pragma warning restore 612, 618
        }
    }
}
